name: chatbot

services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: --wiredTigerCacheSizeGB 1.0
    ports:
      - 27017:27017
    volumes:
      - chatbotdb:/data/db
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - homepage.group=Background Services
      - homepage.name=MongoDB
      - homepage.icon=https://icon.icepanel.io/Technology/svg/MongoDB.svg
      - homepage.description=NoSQL Database
      - com.centurylinklabs.watchtower.enable=false

  chatbot:
    image: chatbot:latest
    container_name: chatbot
    environment:
      GROQ_API_KEY: <your_api_key>
    depends_on:
      - mongodb
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kronosbot.rule=Host(`kronosbot.labserver.com.br`)
      - traefik.http.routers.kronosbot.entrypoints=websecure
      - traefik.http.routers.kronosbot.service=kronosbot
      - traefik.http.services.kronosbot.loadbalancer.server.port=8501
      - traefik.http.routers.kronosbot.tls=true
      - traefik.http.routers.kronosbot.tls.certresolver=cloudflare
      - homepage.group=Applications
      - homepage.name=Kronos Bot
      - homepage.icon=https://img.icons8.com/isometric/60/bot.png
      - homepage.href=https://kronosbot.labserver.com.br
      - homepage.description=AI Chatbot
      - com.centurylinklabs.watchtower.enable=false
    networks:
      - proxy

  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    ports:
      - 4080:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - homepage.group=Applications
      - homepage.name=Mongo Express
      - homepage.icon=https://images.seeklogo.com/logo-png/48/2/mongodb-logo-png_seeklogo-481256.png
      - homepage.href=http://192.168.15.6:4080
      - homepage.description=Database IDE
      - com.centurylinklabs.watchtower.enable=true

networks:
  proxy:
    external: true

volumes:
  chatbotdb:
