name: chatbot

services:
  mongodb:
    image: mongo
    container_name: mongodb
    command: --wiredTigerCacheSizeGB 1.0
    ports:
      - 27017:27017
    volumes:
      - chatbotdb:/data/db
    restart: unless-stopped
    networks:
      - proxy

  chatbot:
    image: chatbot:latest
    container_name: chatbot
    environment:
      GROQ_API_KEY: <your_api_key>
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - proxy

  mongo-express:
    image: mongo-express
    container_name: mongodb-express
    ports:
      - 4080:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

volumes:
  chatbotdb:
